# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56ca150ecaa9b01327d75394ea7a442e646c9c8987977b3c4a3b2d935aedfb51220a1c4b00ab415de3811b238f2b2f44535f44fb2c7c36e59220e33a784eabfa

test:
  secret_key_base: 621386234a6a278c2bea2d1b79b0e4ca22eca9e1e1568a2c946454801902dcd26031ad171e99c67faa12555a19b6a749c69fe1b6c5c8fe6945a0235dd8f47cc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
